site_name: Infernet ML Docs

extra_css:
  - stylesheets/extra.css

theme:
  logo: assets/logo.svg
  name: material
  palette:
    - scheme: slate
      primary: custom
  features:
    - content.tabs.link
    - content.code.copy
    - search.highlight
    - search.suggest

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition

nav:
- Quickstart: quickstart.md
- Reference:
  - infernet_ml:
    - workflows:
      - exceptions: reference/infernet_ml/workflows/exceptions.md
      - utils:
        - common_types: reference/infernet_ml/workflows/utils/common_types.md
      - inference:
        - tgi_client_inference_workflow: reference/infernet_ml/workflows/inference/tgi_client_inference_workflow.md
        - onnx_inference_workflow: reference/infernet_ml/workflows/inference/onnx_inference_workflow.md
        - hf_inference_client_workflow: reference/infernet_ml/workflows/inference/hf_inference_client_workflow.md
        - tts_inference_workflow: reference/infernet_ml/workflows/inference/tts_inference_workflow.md
        - base_inference_workflow: reference/infernet_ml/workflows/inference/base_inference_workflow.md
        - torch_inference_workflow: reference/infernet_ml/workflows/inference/torch_inference_workflow.md
        - css_inference_workflow: reference/infernet_ml/workflows/inference/css_inference_workflow.md
        - bark_hf_inference_workflow: reference/infernet_ml/workflows/inference/bark_hf_inference_workflow.md
    - utils:
      - css_mux: reference/infernet_ml/utils/css_mux.md
      - common_types: reference/infernet_ml/utils/common_types.md
      - service_models: reference/infernet_ml/utils/service_models.md
      - hf_types: reference/infernet_ml/utils/hf_types.md
      - model_loader: reference/infernet_ml/utils/model_loader.md
      - codec:
        - vector: reference/infernet_ml/utils/codec/vector.md
        - css: reference/infernet_ml/utils/codec/css.md
