site_name: Inference Services
nav:
- css_inference_service: reference/css_inference_service.md
- onnx_inference_service: reference/onnx_inference_service.md
- tgi_client_inference_service: reference/tgi_client_inference_service.md
- torch_inference_service: reference/torch_inference_service.md
- hf_inference_client_service: reference/hf_inference_client_service.md
