site_name: Inference Services
extra_css:
- stylesheets/extra.css
theme:
  logo: assets/logo.svg
  name: material
  palette:
  - scheme: slate
    primary: custom
  features:
  - content.tabs.link
  - content.code.copy
  - search.highlight
  - search.suggest
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.tabbed:
    alternate_style: true
- admonition
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
          show_source: true
nav:
- css_inference_service: reference/css_inference_service.md
- onnx_inference_service: reference/onnx_inference_service.md
- tgi_client_inference_service: reference/tgi_client_inference_service.md
- torch_inference_service: reference/torch_inference_service.md
- hf_inference_client_service: reference/hf_inference_client_service.md
