version: '3'

services:
  node:
    image: ritualnetwork/infernet-node-internal:no-filter
    ports:
      - "0.0.0.0:4000:4000"
    volumes:
      - ./config.json:/app/config.json
      - node-logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network
    depends_on:
      - redis
      - anvil-node
    restart:
      on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stop_grace_period: 1m
    container_name: infernet-node

  redis:
    image: redis:latest
    expose:
      - "6379"
    networks:
      - network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    restart:
      on-failure

  fluentbit:
    image: fluent/fluent-bit:latest
    expose:
      - "24224"
    environment:
      - FLUENTBIT_CONFIG_PATH=/fluent-bit/etc/fluent-bit.conf
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/log:/var/log:ro
    networks:
      - network
    restart:
      on-failure

  anvil-node:
      image: ritualnetwork/infernet-anvil-internal:latest
      command: --host 0.0.0.0 --port 3000 --load-state saved_states/everything-deployed.state -b 1
      ports:
        - "8545:3000"
      networks:
        - network
      container_name: anvil-node
#
#  echo:
#    image: ritualnetwork/echo:latest
#    ports:
#      - "3000:3000"
#    networks:
#      - network
#    container_name: echo

networks:
  network:

volumes:
  node-logs:
  redis-data:
