site_name: Infernet Client Docs
extra_css:
- stylesheets/extra.css
theme:
  logo: assets/logo.svg
  name: material
  palette:
  - scheme: slate
    primary: custom
  features:
  - content.tabs.link
  - content.code.copy
  - search.highlight
  - search.suggest
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.tabbed:
    alternate_style: true
- admonition
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
          show_source: true
nav:
- Usage: usage.md
- Reference:
  - infernet_client:
    - error: reference/infernet_client/error.md
    - client: reference/infernet_client/client.md
    - types: reference/infernet_client/types.md
    - chain:
      - token: reference/infernet_client/chain/token.md
      - subscription: reference/infernet_client/chain/subscription.md
      - wallet_factory: reference/infernet_client/chain/wallet_factory.md
      - rpc: reference/infernet_client/chain/rpc.md
      - abis: reference/infernet_client/chain/abis.md
      - wallet: reference/infernet_client/chain/wallet.md
    - cli:
      - options: reference/infernet_client/cli/options.md
      - sample_inputs: []
