site_name: Infernet Client Docs
theme:
  name: material
  features:
  - content.tabs.link
  - content.code.copy
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.tabbed:
    alternate_style: true
- admonition
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
          show_source: true
nav:
- Usage: usage.md
- Reference:
  - infernet_client:
    - error: reference/infernet_client/error.md
    - client: reference/infernet_client/client.md
    - types: reference/infernet_client/types.md
    - chain_utils: reference/infernet_client/chain_utils.md
    - cli:
      - options: reference/infernet_client/cli/options.md
      - sample_inputs: []
