site_name: Infernet Client Docs
theme:
  name: material
  features:
    - content.tabs.link
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
          show_source: true
nav:
- Quickstart: quickstart.md
- Reference:
  - infernet_client:
    - error: reference/infernet_client/error.md
    - client: reference/infernet_client/client.md
    - types: reference/infernet_client/types.md
    - chain_utils: reference/infernet_client/chain_utils.md
    - cli:
      - options: reference/infernet_client/cli/options.md
      - sample_inputs: []
