site_name: Ritual Arweave docs

extra_css:
- stylesheets/extra.css

theme:
  logo: assets/logo.svg
  name: material
  palette:
  - scheme: slate
    primary: custom
  features:
  - content.tabs.link
  - content.code.copy
  - search.highlight
  - search.suggest
  
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
          show_source: true

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.tabbed:
    alternate_style: true
- admonition

nav:
- Quickstart: quickstart.md
- Reference:
  - ritual_arweave:
    - repo_manager: reference/ritual_arweave/repo_manager.md
    - types: reference/ritual_arweave/types.md
    - cli: reference/ritual_arweave/cli.md
    - utils: reference/ritual_arweave/utils.md
    - file_manager: reference/ritual_arweave/file_manager.md
