site_name: Ritual Arweave docs
theme:
  name: material
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
          show_source: true
nav:
- Quickstart: quickstart.md
- Reference:
  - ritual_arweave:
    - repo_manager: ritual_arweave/repo_manager.md
    - types: ritual_arweave/types.md
    - cli: ritual_arweave/cli.md
    - utils: ritual_arweave/utils.md
    - file_manager: ritual_arweave/file_manager.md
