site_name: Infernet ML docs
theme:
  name: material
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
          show_source: true
nav:
- infernet_ml:
  - workflows:
    - exceptions: infernet_ml/workflows/exceptions.md
    - utils:
      - common_types: infernet_ml/workflows/utils/common_types.md
    - inference:
      - tgi_client_inference_workflow: infernet_ml/workflows/inference/tgi_client_inference_workflow.md
      - onnx_inference_workflow: infernet_ml/workflows/inference/onnx_inference_workflow.md
      - hf_inference_client_workflow: infernet_ml/workflows/inference/hf_inference_client_workflow.md
      - tts_inference_workflow: infernet_ml/workflows/inference/tts_inference_workflow.md
      - base_inference_workflow: infernet_ml/workflows/inference/base_inference_workflow.md
      - torch_inference_workflow: infernet_ml/workflows/inference/torch_inference_workflow.md
      - css_inference_workflow: infernet_ml/workflows/inference/css_inference_workflow.md
      - bark_hf_inference_workflow: infernet_ml/workflows/inference/bark_hf_inference_workflow.md
  - utils:
    - css_mux: infernet_ml/utils/css_mux.md
    - common_types: infernet_ml/utils/common_types.md
    - service_models: infernet_ml/utils/service_models.md
    - hf_types: infernet_ml/utils/hf_types.md
    - model_loader: infernet_ml/utils/model_loader.md
    - codec:
      - vector: infernet_ml/utils/codec/vector.md
      - css: infernet_ml/utils/codec/css.md
