name: Deploy to Vercel

on:
  pull_request:
    paths:
      - 'libraries/**'
      - '.github/workflows/docs_deploy.yaml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        library: [ "infernet_ml", "infernet_client", "ritual_arweave" ]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install UV & setup python env
        run: |
          python -m pip install uv
          uv venv
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          uv pip install -r pyproject.toml

      - name: setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install Vercel CLI
        run: bun install --global vercel@latest

      - name: Build & Generate docs
        run: make deploy-docs library=${{ matrix.library }}
