name: Deploy to Vercel

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ "infernet_ml" ]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install UV & setup python env
        run: |
          python -m pip install uv
          uv venv

      - name: Activate virtual environment
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Install dependencies
        run: uv pip install -r pyproject.toml

      - name: Add venv bin to PATH
        run: echo PATH=".venv/bin/:$PATH" >> $GITHUB_ENV

      - name: Generate docs
        run: make generate-docs project=${{ matrix.project }}

      - name: Build docs
        env:
          PYTHONPATH: ./projects/${{ matrix.project }}/src
        run: make build-docs project=${{ matrix.project }}

      - name: Vercel Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Vercel token
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # Vercel organization ID
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # Vercel project ID
          vercel-args: '--prod'  # Additional Vercel CLI arguments
