name: Deploy to Vercel

on:
  pull_request:
    paths:
      - 'libraries/**'
      - '.github/workflows/docs_deploy.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        library: [ "infernet_ml", "ritual_arweave" ]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install UV & setup python env
        run: |
          python -m pip install uv
          uv venv
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          uv pip install -r pyproject.toml

      - name: Build & Generate docs
        env:
          PYTHONPATH: src
        run: make generate-docs build-docs library=${{ matrix.library }}


      - name: Upload docs as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs-${{ matrix.library }}
          path: libraries/${{ matrix.library }}/site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download docs artifacts
        uses: actions/download-artifact@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install UV & setup python env
        run: |
          python -m pip install uv
          uv venv
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          uv pip install -r pyproject.toml

      - name: Build & Generate docs
        env:
          PYTHONPATH: src
        run: make build-docs-index

      - name: Vercel Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'