name: Deploy to Vercel

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install UV & setup python env
        run: |
          python -m pip install uv
          uv venv
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          uv pip install -r pyproject.toml

      - name: Vercel Deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Vercel token
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # Vercel organization ID
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # Vercel project ID
          vercel-args: '--prod'  # Additional Vercel CLI arguments
