# pre-commit workflow
#
# Ensures the codebase passes the pre-commit stack.

name: Infernet Services Pre-commits, Style, and Linting

on:
  pull_request:
    paths:
      - 'infernet_services/**'
      - '.github/workflows/infernet_services_precommit.yaml'

jobs:
  python_precommits:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install UV
      run: python -m pip install uv

    # Can't install from uv with the --system flag much like what we do in our
    # dockerfiles, because we'd have to run it as root.
    - name: Create virtual environment
      run: uv venv

    - name: Activate virtual environment
      run: |
        . .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        uv pip install -r infernet_services/requirements-precommit.lock
        uv pip install -r pyproject.toml

    - name: Run pre-commit hooks
      run: make pre-commit-services
