# pre-commit workflow for Infernet Monorepo

name: Python Libraries CI

on:
  pull_request:
    paths:
      - 'libraries/**'
      - '.github/workflows/python_projects_ci.yaml'

jobs:
  monorepo_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        library: [ "infernet_client", "infernet_ml", "ritual_arweave" ]
        python-version: [ "3.10", "3.11" ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # pull submodules manually
      - run: |
          git submodule sync --recursive
          git -c protocol.version=2 submodule update --init --force --depth=1 --recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UV
        run: python -m pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Activate virtual environment
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      # first line is the project's specific dependencies,
      - name: Install dependencies
        run: |
          uv pip install -r libraries/${{ matrix.library }}/requirements.lock
          uv pip install -r pyproject.toml

      - name: Run pre-commit hooks
        run: make pre-commit-library library=${{ matrix.library }}
